# Generated by Django 6.0.5 on 2026-05-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_scanhistory_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="scanhistory",
            name="uploaded_file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
