# Generated by Django 6.0.5 on 2026-05-23 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0003_scanhistory_uploaded_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scanhistory",
            name="uploaded_file",
        ),
        migrations.AddField(
            model_name="scanhistory",
            name="filename",
            field=models.CharField(default="unnamed_stream.txt", max_length=255),
        ),
        migrations.AlterField(
            model_name="scanhistory",
            name="risk_level",
            field=models.CharField(default="LOW", max_length=10),
        ),
        migrations.AlterField(
            model_name="scanhistory",
            name="risk_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="scanhistory",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
