"""
Django settings for privacy_project project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import urllib.parse as urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load local .env if it exists (for local development environment override)
env_path = BASE_DIR / '.env'
if env_path.exists():
    with open(env_path, 'r') as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith('#') and '=' in line:
                key, val = line.split('=', 1)
                # Strip optional quotes
                val = val.strip('\'"')
                os.environ.setdefault(key.strip(), val)

MEDIA_URL='/media/'
MEDIA_ROOT='media'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-local-dev-fallback-key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '127.0.0.1:8000', 'localhost:8000']
env_allowed_hosts = os.environ.get('ALLOWED_HOSTS')
if env_allowed_hosts:
    ALLOWED_HOSTS.extend([host.strip() for host in env_allowed_hosts.split(',') if host.strip()])
else:
    ALLOWED_HOSTS.append('.onrender.com')

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'corsheaders',
    'scanner',
    'rest_framework_simplejwt',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ]
}
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Whitenoise middleware for production static files serving
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "privacy_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "privacy_project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database Configuration supporting both DATABASE_URL and individual variables
DATABASE_URL = os.environ.get('DATABASE_URL', '').strip().strip('\'"')

# Strip accidental variable prefix if pasted directly into value field on Render
if DATABASE_URL.startswith('DATABASE_URL='):
    DATABASE_URL = DATABASE_URL[len('DATABASE_URL='):].strip().strip('\'"')
elif DATABASE_URL.startswith('database_url='):
    DATABASE_URL = DATABASE_URL[len('database_url='):].strip().strip('\'"')

if DATABASE_URL and '://' in DATABASE_URL:
    url = urlparse.urlparse(DATABASE_URL)
    query_params = urlparse.parse_qs(url.query)
    
    db_name = url.path.lstrip('/') if url.path else 'postgres'
    if not db_name or '/' in db_name:
        db_name = 'postgres'
    
    db_config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': urlparse.unquote(db_name),
        'USER': urlparse.unquote(url.username or 'postgres'),
        'PASSWORD': urlparse.unquote(url.password or ''),
        'HOST': url.hostname,
        'PORT': url.port or '5432',
    }
    
    options = {}
    if 'sslmode' in query_params:
        options['sslmode'] = query_params['sslmode'][0]
    else:
        if 'supabase' in (url.hostname or ''):
            options['sslmode'] = 'require'
            
    if options:
        db_config['OPTIONS'] = options
        
    DATABASES = {
        'default': db_config
    }
else:
    db_host = os.environ.get('DB_HOST', '').strip().strip('\'"')
    db_name = os.environ.get('DB_NAME', 'postgres').strip().strip('\'"')
    if not db_name or '://' in db_name:
        db_name = 'postgres'
        
    db_config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': db_name,
        'USER': os.environ.get('DB_USER', 'postgres').strip().strip('\'"'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '').strip().strip('\'"'),
        'HOST': db_host,
        'PORT': os.environ.get('DB_PORT', '5432').strip().strip('\'"'),
    }
    
    if 'supabase' in db_host:
        db_config['OPTIONS'] = {
            'sslmode': 'require',
        }
        
    DATABASES = {
        'default': db_config
    }   


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Whitelist the React Vite frontend development port
# CORS origins configuration
CORS_ALLOW_CREDENTIALS = True

# Allow all origins by default in development, or if specified in environment
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True') == 'True'

cors_origins_env = os.environ.get('CORS_ALLOWED_ORIGINS')
if cors_origins_env:
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(',') if origin.strip()]
    CORS_ALLOW_ALL_ORIGINS = False
else:
    CORS_ALLOWED_ORIGINS = [
        "https://privacy-shield-ai-ten.vercel.app",
        "http://localhost:3000",
        "http://127.0.0.1:3000",
        "http://localhost:5173",
        "http://127.0.0.1:5173",
    ]

# Whitenoise storage configuration for compressing static files on build
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
